# Generated by Django 4.2.5 on 2023-09-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buy', '0006_product_permission_delete_index_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
