# Generated by Django 4.2.5 on 2023-09-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buy', '0007_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cart',
            name='choices',
            field=models.CharField(choices=[('1', 'Process'), ('2', 'Completed')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='quantity'),
            preserve_default=False,
        ),
    ]
