# Generated by Django 4.2.5 on 2023-09-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buy', '0010_remove_order_name_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payment_id',
            field=models.CharField(default=1, max_length=36, verbose_name='Payment ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='provider_order_id',
            field=models.CharField(default=1, max_length=40, verbose_name='Order ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='signature_id',
            field=models.CharField(default=1, max_length=128, verbose_name='Signature ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('PENDING', 'Pending')], default='PENDING', max_length=254, verbose_name='Payment Status'),
        ),
    ]
